Repository sicmutils/sicmutils, pull requests merged in 2022-01, with the labels that each got.

#445 Fix for pattern matcher accidentally seq-ing structures, etc
  CHANGELOG.md
  src/pattern/match.cljc
  src/sicmutils/simplify.cljc
  test/sicmutils/structure_test.cljc
Labels: bug, Pattern Matching

#458 Allow for symbolic rational functions, fix for ->expression
  CHANGELOG.md
  src/sicmutils/abstract/number.cljc
  src/sicmutils/polynomial.cljc
  src/sicmutils/polynomial/gcd.cljc
  src/sicmutils/rational_function.cljc
  test/sicmutils/polynomial/gcd_test.cljc
  test/sicmutils/polynomial_test.cljc
  test/sicmutils/rational_function_test.cljc
Labels: enhancement

#449 new sinc, sinhc, tanc, tanhc generics + remaining trig functions
  CHANGELOG.md
  src/sicmutils/abstract/number.cljc
  src/sicmutils/differential.cljc
  src/sicmutils/env.cljc
  src/sicmutils/generic.cljc
  src/sicmutils/numbers.cljc
  src/sicmutils/numsymb.cljc
  src/sicmutils/series.cljc
  test/sicmutils/abstract/number_test.cljc
  test/sicmutils/differential_test.cljc
  test/sicmutils/numbers_test.cljc
Labels: kernel

#461 Quaternion implementation
  CHANGELOG.md
  src/data_readers.cljc
  src/sicmutils/complex.cljc
  src/sicmutils/env.cljc
  src/sicmutils/env/sci.cljc
  src/sicmutils/quaternion.cljc
  test/sicmutils/differential_test.cljc
  test/sicmutils/generators.cljc
  test/sicmutils/quaternion_test.cljc
Labels: type, kernel

#398 Add gcd implementation for complex numbers
  src/sicmutils/euclid.cljc
  test/sicmutils/euclid_test.cljc
Labels: kernel

#469 solve-linear and missing generic implementations for Matrix
  CHANGELOG.md
  src/sicmutils/matrix.cljc
  src/sicmutils/mechanics/hamilton.cljc
  src/sicmutils/mechanics/lagrange.cljc
  src/sicmutils/operator.cljc
  src/sicmutils/series/impl.cljc
  src/sicmutils/structure.cljc
  src/sicmutils/util/permute.cljc
  test/sicmutils/matrix_test.cljc
  test/sicmutils/structure_test.cljc
Labels: kernel
